import { FixtureWarmupQuestion } from '../fixtures/hyrte-fixture.types';

/**
 * Founder feedback (WhatsApp, 9 Sep): "I've noticed some questions are very
 * repeated in pm role, bakio me bhi honge — isse fix kro. Kuch bhi repeat nhi
 * hona chahiye."
 *
 * The baseline warm-up questions were generated by one LLM call per session
 * whose only variety input was a random 6-char nonce. That is not enough: ask
 * any model for "warm-up questions for a Product Manager" and it converges on
 * the same handful of canonical questions (validate a feature idea, prioritize
 * a roadmap, define success metrics) no matter what nonce you attach — exactly
 * the repetition that was observed. `priorWarmupQuestions` existed as an
 * avoid-list but was only ever populated for ASSESSMENT sessions launched from
 * a recruiter link; self-serve PRACTICE sessions (which is what the founder was
 * running) passed no grounding at all, so nothing suppressed repeats there.
 *
 * This module is the deterministic half of the fix — the same discipline used
 * elsewhere in this codebase (hiddenIntention omission, EVn-label stripping,
 * repetition detection): don't rely on the LLM noticing it is repeating itself.
 *
 *  1. `pickAxes` hands the generator an explicit, rotated set of competency
 *     axes to write questions about — different axes per session, walked
 *     round-robin off the candidate's own prior-session count, so two
 *     consecutive sessions in the same role cannot even be asked to cover the
 *     same ground.
 *  2. `enforceWarmupVariety` runs AFTER generation and drops anything that is
 *     still a near-duplicate (of a prior session's question or of a sibling in
 *     the same set), backfilling from a real per-axis question bank rather than
 *     shipping the duplicate.
 */

export interface RoleAxisPool {
  /** Named competency sub-topics for this role family. */
  axes: string[];
  /** One real, usable question per axis — the deterministic backfill when generation repeats itself. */
  bank: Record<string, string[]>;
}

/**
 * Role is free text (candidate self-serve picker OR a recruiter's JD-decompose
 * flow), so this resolves by REGEX over real job-title language, same as
 * `signature-artifacts.ts` — not an exact-match table.
 */
const ROLE_AXIS_POOLS: { pattern: RegExp; pool: RoleAxisPool }[] = [
  {
    pattern: /product manager|\bpm\b|product owner/i,
    pool: {
      axes: [
        'discovery & user research',
        'prioritization under constraint',
        'success metrics & instrumentation',
        'writing & specification',
        'working with engineering',
        'pricing & packaging',
        'launch & go-to-market',
        'churn & retention diagnosis',
        'experimentation & A/B testing',
        'stakeholder disagreement',
        'technical debt trade-offs',
        'competitive response',
      ],
      bank: {
        'discovery & user research': [
          'You have five customer calls booked this week and one hypothesis. How do you structure those calls so you learn something you could be wrong about?',
          'A sales rep insists customers are asking for a feature. What would you do before putting it on the roadmap?',
        ],
        'prioritization under constraint': [
          'Engineering can ship exactly one of two things this quarter and both have a named customer attached. What information do you gather to decide?',
          'Your roadmap is full and your manager adds something new without removing anything. What do you actually do?',
        ],
        'success metrics & instrumentation': [
          'A feature launched and usage looks flat. What would you check first to tell "nobody wants it" apart from "nobody can find it"?',
          'You are asked to pick one number to represent whether your product is healthy. Which would you pick and what does it miss?',
        ],
        'writing & specification': [
          'What belongs in a spec that engineers will actually read, and what do you deliberately leave out?',
          'How do you write acceptance criteria for something whose scope is still genuinely uncertain?',
        ],
        'working with engineering': [
          'An engineer tells you an estimate is three weeks and you believe it should be three days. How do you handle that conversation?',
          'Mid-sprint, engineering discovers the approach will not work. What do you do in the next hour?',
        ],
        'pricing & packaging': [
          'Two customers want the same capability but only one will pay for it. How does that shape how you package it?',
          'How would you decide whether something belongs in the base tier or an add-on?',
        ],
        'launch & go-to-market': [
          'What has to be true before you would agree to a launch date in front of the CEO?',
          'How do you decide between a limited rollout and a full launch when the data is ambiguous?',
        ],
        'churn & retention diagnosis': [
          'Churn moved up half a point this month. Walk through how you find out whether that is signal or noise.',
          'What would tell you a churn problem is a product problem rather than a sales-fit problem?',
        ],
        'experimentation & A/B testing': [
          'When is running an experiment the wrong call, and what would you do instead?',
          'An A/B test comes back flat. What do you conclude, and what do you refuse to conclude?',
        ],
        'stakeholder disagreement': [
          'Sales and engineering want opposite things and both escalated to you. What is your first move?',
          'Your manager overrules a decision you have evidence for. What do you do next?',
        ],
        'technical debt trade-offs': [
          'How do you make the case for paying down technical debt to someone who only cares about shipped features?',
          'What signal tells you debt has crossed from tolerable into actively expensive?',
        ],
        'competitive response': [
          'A competitor ships the feature you had planned for next quarter. What changes and what does not?',
          'How do you decide whether to respond to a competitor at all?',
        ],
      },
    },
  },
  {
    pattern: /software engineer|developer|full[- ]?stack|backend|frontend|\bswe\b/i,
    pool: {
      axes: [
        'debugging a production issue',
        'code review judgment',
        'system design trade-offs',
        'testing strategy',
        'performance investigation',
        'refactoring & legacy code',
        'incident response & on-call',
        'API & interface design',
        'data modelling',
        'deployment & rollback',
        'estimating work',
        'security basics',
      ],
      bank: {
        'debugging a production issue': [
          'An endpoint fails for roughly one request in fifty and you cannot reproduce it locally. Where do you start?',
          'Logs show an error that the metrics dashboard says never happened. How do you reconcile that?',
        ],
        'code review judgment': [
          'A pull request works but you would have built it differently. When is that worth blocking on?',
          'How do you review a change in an area of the codebase you do not know?',
        ],
        'system design trade-offs': [
          'When would you deliberately choose the simpler design you know will need replacing?',
          'How do you decide whether something belongs in a new service or in the one you already have?',
        ],
        'testing strategy': [
          'Which tests would you write first for a feature that touches payments, and why those?',
          'A test suite is slow and flaky. What do you fix first?',
        ],
        'performance investigation': [
          'Latency at p99 tripled but p50 is unchanged. What does that pattern suggest and how do you confirm it?',
          'How do you tell a slow query apart from a slow network hop without guessing?',
        ],
        'refactoring & legacy code': [
          'You need to change code with no tests and no original author. How do you make that safe?',
          'How do you scope a refactor so it does not become open-ended?',
        ],
        'incident response & on-call': [
          'You are paged at 2am and the obvious fix is a restart. What do you do before and after restarting?',
          'What makes a postmortem useful rather than a formality?',
        ],
        'API & interface design': [
          'What makes an API painful to consume, and how do you catch that before shipping it?',
          'How would you version a breaking change that two internal teams already depend on?',
        ],
        'data modelling': [
          'When would you denormalize deliberately, and what do you accept in exchange?',
          'How do you handle a migration on a table that cannot be locked?',
        ],
        'deployment & rollback': [
          'What has to be in place before you would be comfortable deploying on a Friday?',
          'A deploy looks fine but support tickets are rising. How do you decide whether to roll back?',
        ],
        'estimating work': [
          'How do you estimate something you have never built before without inventing a number?',
          'You are halfway through and it is clearly going to take twice as long. When and how do you say so?',
        ],
        'security basics': [
          'Where would you expect user input to be able to hurt you in a typical web service?',
          'A dependency has a published vulnerability. How do you decide how urgently to act?',
        ],
      },
    },
  },
  {
    pattern: /data (scientist|analyst)|analytics|machine learning|\bml\b/i,
    pool: {
      axes: [
        'framing an ambiguous question',
        'data quality & trust',
        'causal vs correlational reasoning',
        'metric definition',
        'communicating findings',
        'experiment design',
        'model evaluation',
        'stakeholder pushback',
        'segmentation',
        'forecasting',
      ],
      bank: {
        'framing an ambiguous question': [
          'An executive asks "why is growth down?" with no further context. What do you ask before touching data?',
          'How do you turn a vague request into something you can actually answer with the data you have?',
        ],
        'data quality & trust': [
          'A number in a dashboard looks wrong. How do you establish whether it is wrong before escalating?',
          'What checks do you run on a dataset you have never used before?',
        ],
        'causal vs correlational reasoning': [
          'Two metrics moved together last quarter. What would you need to claim one caused the other?',
          'How do you explain to a non-technical stakeholder why a correlation is not enough?',
        ],
        'metric definition': [
          'Two teams report different numbers for the same metric. How do you resolve it?',
          'What makes a metric easy to game, and how do you design against that?',
        ],
        'communicating findings': [
          'Your analysis contradicts what leadership already announced publicly. How do you present it?',
          'How do you present an inconclusive result without it being dismissed?',
        ],
        'experiment design': [
          'How do you decide how long to run a test before looking at it?',
          'What would make you refuse to run an A/B test on something?',
        ],
        'model evaluation': [
          'Accuracy is high and the model is still useless in production. How does that happen?',
          'Which failure mode would you check for first in a model that flags risk?',
        ],
        'stakeholder pushback': [
          'Someone rejects your analysis because they do not like the answer. What do you do?',
          'How do you handle being asked to re-run an analysis until it says something different?',
        ],
        segmentation: [
          'How do you decide whether an aggregate number is hiding two different stories?',
          'What makes a segmentation useful rather than just more slices?',
        ],
        forecasting: [
          'What assumptions in a forecast do you make explicit, and why those?',
          'Your forecast was wrong. How do you work out whether the model or the world changed?',
        ],
      },
    },
  },
  {
    pattern: /sales|account (executive|manager)|\bsdr\b|\bbdr\b|business development|customer success/i,
    pool: {
      axes: [
        'qualification & disqualification',
        'discovery questioning',
        'objection handling',
        'multi-threading a deal',
        'pricing & discounting',
        'forecasting honesty',
        'losing a deal well',
        'renewals & expansion',
        'working with product',
        'handling an unhappy customer',
      ],
      bank: {
        'qualification & disqualification': [
          'What would make you walk away from a deal that looks big on paper?',
          'How do you tell genuine interest apart from polite interest on a first call?',
        ],
        'discovery questioning': [
          'What do you want to know by the end of a first call that you cannot get from their website?',
          'A prospect answers everything in generalities. How do you get specific?',
        ],
        'objection handling': [
          'A prospect says you are too expensive. What do you actually want to find out before responding?',
          'How do you handle an objection you privately think is correct?',
        ],
        'multi-threading a deal': [
          'Your only contact goes quiet two weeks before close. What do you do?',
          'How do you get access to a decision-maker without going around your champion?',
        ],
        'pricing & discounting': [
          'When is a discount the right call, and what do you ask for in return?',
          'How do you protect price when a competitor undercuts you outright?',
        ],
        'forecasting honesty': [
          'What makes you move a deal out of this quarter rather than hoping?',
          'How do you tell your manager a committed deal is slipping?',
        ],
        'losing a deal well': [
          'You lost. What do you do in the following week that has any value?',
          'How do you get an honest answer about why you lost?',
        ],
        'renewals & expansion': [
          'What signal a quarter out tells you a renewal is at risk?',
          'How do you expand an account without irritating the person who already bought?',
        ],
        'working with product': [
          'A prospect needs something that does not exist. How do you handle that internally and externally?',
          'How do you give product feedback that actually gets acted on?',
        ],
        'handling an unhappy customer': [
          'A customer threatens to leave over an outage you cannot fix today. What do you say on that call?',
          'How do you rebuild trust with an account after you personally got something wrong?',
        ],
      },
    },
  },
  {
    pattern: /marketing|growth|brand|content/i,
    pool: {
      axes: [
        'positioning & messaging',
        'channel selection',
        'campaign measurement',
        'budget allocation',
        'audience & segmentation',
        'launch coordination',
        'content strategy',
        'working with sales',
        'brand vs performance trade-offs',
        'responding to a competitor',
      ],
      bank: {
        'positioning & messaging': [
          'How do you test whether positioning is landing before you spend money on it?',
          'Your product does five things. How do you decide which one leads?',
        ],
        'channel selection': [
          'How do you decide whether a channel is genuinely not working or just not working yet?',
          'What would make you kill a channel that leadership likes?',
        ],
        'campaign measurement': [
          'A campaign drove traffic but no pipeline. What do you look at to find out why?',
          'How do you attribute a deal that touched six channels?',
        ],
        'budget allocation': [
          'Your budget is cut by a third mid-quarter. What goes first?',
          'How do you justify spend on something whose payback is six months out?',
        ],
        'audience & segmentation': [
          'How do you tell whether you are targeting too broadly?',
          'What do you do when the audience actually buying is not the one you designed for?',
        ],
        'launch coordination': [
          'What has to be ready across other teams before you would commit to a launch date?',
          'The product slips a week after your campaign is live. What do you do?',
        ],
        'content strategy': [
          'How do you decide what content is worth making when everything is technically possible?',
          'What makes content useful to sales rather than just to the funnel?',
        ],
        'working with sales': [
          'Sales says the leads are bad. How do you find out whether that is true?',
          'How do you agree on what counts as a qualified lead?',
        ],
        'brand vs performance trade-offs': [
          'How do you defend brand spend to someone who only trusts last-click attribution?',
          'When would you deliberately accept worse short-term numbers?',
        ],
        'responding to a competitor': [
          'A competitor publicly claims something about your product that is misleading. What do you do?',
          'How do you decide whether to name a competitor in your own messaging?',
        ],
      },
    },
  },
  {
    pattern: /designer|\bux\b|\bui\b|product design/i,
    pool: {
      axes: [
        'research & validation',
        'defending a design decision',
        'accessibility',
        'design systems & consistency',
        'scoping under constraint',
        'handoff to engineering',
        'usability testing',
        'information architecture',
        'working from ambiguous requirements',
        'iterating after launch',
      ],
      bank: {
        'research & validation': [
          'How do you validate a flow before anyone builds it?',
          'What do you do when research contradicts a decision already made?',
        ],
        'defending a design decision': [
          'A stakeholder wants a change you believe harms the user. How do you handle it?',
          'How do you argue for a decision when you have opinion but not data?',
        ],
        accessibility: [
          'What would you check first to know whether a screen is usable by someone using a screen reader?',
          'How do you handle accessibility work when the deadline is already tight?',
        ],
        'design systems & consistency': [
          'When is it right to break your own design system?',
          'How do you keep a system usable as the number of contributors grows?',
        ],
        'scoping under constraint': [
          'Engineering can build half of your design. How do you decide which half?',
          'How do you design something that degrades well when parts are cut?',
        ],
        'handoff to engineering': [
          'What do engineers most often need from you that designs alone do not give them?',
          'How do you handle it when what shipped does not match what you designed?',
        ],
        'usability testing': [
          'How many people do you need to test with before you act, and what changes that number?',
          'A user struggles but says the design is fine. Which do you believe?',
        ],
        'information architecture': [
          'How do you decide what deserves to be in primary navigation?',
          'What tells you a structure is confusing rather than just unfamiliar?',
        ],
        'working from ambiguous requirements': [
          'You are handed a one-line request. What do you do before opening a design tool?',
          'How do you design when the underlying business model is still being decided?',
        ],
        'iterating after launch': [
          'A design launched and the numbers got worse. How do you work out what to change?',
          'How do you decide between iterating and reverting?',
        ],
      },
    },
  },
];

/**
 * Role families with no dedicated pool above still get real rotation — the
 * axes are phrased generically enough to apply to any professional role, and
 * the generator is told to write them FOR THIS ROLE specifically.
 */
const GENERIC_POOL: RoleAxisPool = {
  axes: [
    'diagnosing a problem from incomplete information',
    'prioritizing competing demands',
    'communicating bad news upward',
    'working across teams',
    'deciding without enough data',
    'defining what success looks like',
    'handling a mistake',
    'managing time under pressure',
    'pushing back on a request',
    'learning an unfamiliar domain quickly',
  ],
  bank: {
    'diagnosing a problem from incomplete information': [
      'Something in your area is clearly going wrong but nobody can say what. Where do you start?',
      'How do you tell a symptom apart from a cause when both are visible?',
    ],
    'prioritizing competing demands': [
      'Two people senior to you want different things from you today. What do you do?',
      'How do you decide what genuinely does not get done this week?',
    ],
    'communicating bad news upward': [
      'You are going to miss a commitment. When do you say so and what do you bring with you?',
      'How do you raise a risk that leadership has already dismissed once?',
    ],
    'working across teams': [
      'A team you depend on is not delivering. What do you do before escalating?',
      'How do you get help from someone who does not report to you and is already busy?',
    ],
    'deciding without enough data': [
      'What do you do when the decision cannot wait for the data you want?',
      'How do you make a reversible decision differently from an irreversible one?',
    ],
    'defining what success looks like': [
      'You are given a goal with no measure attached. How do you make it measurable?',
      'What would tell you a month in that you are working on the wrong thing?',
    ],
    'handling a mistake': [
      'You made a call that turned out badly and nobody has noticed yet. What do you do?',
      'How do you correct course without losing the team’s confidence?',
    ],
    'managing time under pressure': [
      'Everything on your list is marked urgent. How do you actually sequence the day?',
      'What do you protect time for even in a bad week?',
    ],
    'pushing back on a request': [
      'How do you say no to someone senior without it being a confrontation?',
      'What do you offer instead when you decline something?',
    ],
    'learning an unfamiliar domain quickly': [
      'You have three days to get credible in an area you know nothing about. What do you do?',
      'Who do you talk to first in a company you just joined, and what do you ask?',
    ],
  },
};

export function resolveAxisPool(role: string): RoleAxisPool {
  return ROLE_AXIS_POOLS.find((entry) => entry.pattern.test(role))?.pool ?? GENERIC_POOL;
}

/**
 * Deterministic rotation: session N for a given candidate+role starts at a
 * different offset in the pool than session N-1, so consecutive sessions
 * cannot be asked to cover the same competencies at all. `priorSessionCount`
 * is the candidate's own real count of prior sessions in this role.
 */
export function pickAxes(role: string, count: number, priorSessionCount: number): string[] {
  const { axes } = resolveAxisPool(role);
  const start = (priorSessionCount * count) % axes.length;
  return Array.from({ length: Math.min(count, axes.length) }, (_, i) => axes[(start + i) % axes.length]);
}

/**
 * Question wording varies in ways that carry no meaning — "prioritise" vs
 * "prioritize", "your roadmap" vs "the roadmap", "is urgent" vs "feels
 * urgent". Raw Jaccard over every word (what the interview's own
 * answer-repetition detector does) scores that pair at 0.54 and lets the
 * reword through, which is precisely the "lightly reworded repeat" the
 * founder flagged. Comparing CONTENT words only — stopwords dropped, spelling
 * and plurals normalized — scores the same pair at 1.0.
 */
const STOPWORDS = new Set([
  'a', 'an', 'and', 'are', 'as', 'at', 'be', 'been', 'but', 'by', 'can', 'could', 'did', 'do', 'does', 'for',
  'from', 'had', 'has', 'have', 'how', 'i', 'if', 'in', 'into', 'is', 'it', 'its', 'just', 'me', 'my', 'of',
  'on', 'or', 'our', 'out', 'over', 'should', 'so', 'some', 'something', 'than', 'that', 'the', 'their',
  'them', 'then', 'there', 'these', 'they', 'this', 'to', 'up', 'was', 'we', 'were', 'what', 'when', 'which',
  'while', 'who', 'why', 'will', 'with', 'would', 'you', 'your', 'yours',
]);

function contentWords(text: string): Set<string> {
  return new Set(
    text
      .toLowerCase()
      .split(/\W+/)
      .filter(Boolean)
      .map((w) => w.replace(/(is|iz)(e|ed|es|ing|ation)$/, 'ize').replace(/(ies|es|s)$/, ''))
      .filter((w) => w.length > 2 && !STOPWORDS.has(w)),
  );
}

/** Jaccard over content words — deterministic, no LLM call. */
export function questionSimilarity(a: string, b: string): number {
  const setA = contentWords(a);
  const setB = contentWords(b);
  if (setA.size === 0 || setB.size === 0) return 0;
  let intersection = 0;
  for (const word of setA) if (setB.has(word)) intersection++;
  const union = setA.size + setB.size - intersection;
  return union === 0 ? 0 : intersection / union;
}

const DUPLICATE_THRESHOLD = 0.5;

function isDuplicate(question: string, against: string[]): boolean {
  return against.some((other) => questionSimilarity(question, other) >= DUPLICATE_THRESHOLD);
}

/**
 * The deterministic guarantee behind "kuch bhi repeat nhi hona chahiye": any
 * generated question that is a near-duplicate of one this candidate already
 * saw in this role — or of a sibling in the same set — is dropped and replaced
 * from the axis bank. Runs after generation, so it holds even when the model
 * ignores both the axis list and the avoid-list in the prompt.
 *
 * Returns exactly `expectedCount` questions whenever the bank can supply them.
 */
export function enforceWarmupVariety(
  questions: FixtureWarmupQuestion[],
  role: string,
  priorQuestions: string[],
  axes: string[],
  expectedCount: number,
): FixtureWarmupQuestion[] {
  const pool = resolveAxisPool(role);
  const kept: FixtureWarmupQuestion[] = [];
  const seen = [...priorQuestions];

  for (const q of questions) {
    if (kept.length >= expectedCount) break;
    if (isDuplicate(q.question, seen)) continue;
    kept.push(q);
    seen.push(q.question);
  }

  if (kept.length >= expectedCount) return kept;

  // Backfill from the bank, preferring this session's own assigned axes and
  // skipping any bank entry that is itself a near-duplicate of what the
  // candidate has already been asked.
  const orderedAxes = [...axes, ...pool.axes.filter((a) => !axes.includes(a))];
  for (const axis of orderedAxes) {
    for (const candidate of pool.bank[axis] ?? []) {
      if (kept.length >= expectedCount) return kept;
      if (isDuplicate(candidate, seen)) continue;
      kept.push({ id: `wq-${axis.replace(/[^a-z]+/gi, '-').toLowerCase()}-${kept.length + 1}`, question: candidate });
      seen.push(candidate);
    }
  }
  return kept;
}
